AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SearchAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          /smf/instrument/{symbol+}:
            any:
              x-amazon-apigateway-integration:
                httpMethod: ANY
                type: aws_proxy
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchFunction.Arn}/invocations
              responses: {}
  SearchFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: com.smf.search.SearchFunction::handleRequest
      Timeout: 60
      CodeUri: ./target/search.jar
      MemorySize: 128
      Role: smf-query
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /smf/instrument/{symbol+}
            Method: any
            RestApiId:
              Ref: SearchAPI

